In [3]:
import pandas as pd
import numpy as np
import tscv

In [4]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=2000,
    n_features=300,
    n_informative=50,
    n_redundant=100,
    n_repeated=3,
    n_classes=2,
    n_clusters_per_class=1,
    class_sep=0.8,
    random_state=0,
)

In [12]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import StratifiedKFold, TimeSeriesSplit
from catboost import CatBoostClassifier

min_features_to_select = 100
clf = CatBoostClassifier(verbose=0)
cv = tscv.GapKFold(n_splits=3, gap_before=200, gap_after=200)

sfs = SequentialFeatureSelector(
    estimator=clf,
    n_features_to_select="auto",
    tol=0.001,
    direction="forward",
    scoring="f1",
    cv=cv
)

In [ ]:
sfs.fit(X, y)

In [9]:
sfs.get_feature_names_out()

array([ True, False,  True, False, False,  True, False, False, False,
        True,  True,  True,  True, False,  True,  True, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True, False,
        True, False, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False,  True,
        True, False, False, False, False, False,  True,  True, False,
        True,  True, False, False, False, False, False,  True, False,
        True, False,  True, False, False, False, False, False, False,
        True, False, False,  True,  True,  True, False, False,  True,
       False, False,  True, False,  True, False, False,  True, False,
        True, False,  True,  True,  True, False, False, False,  True,
       False, False,  True, False,  True, False, False, False, False,
       False,  True,

In [10]:
sfs.get_support()

array(['x0', 'x2', 'x5', 'x9', 'x10', 'x11', 'x12', 'x14', 'x15', 'x21',
       'x22', 'x32', 'x33', 'x34', 'x36', 'x41', 'x45', 'x49', 'x57',
       'x58', 'x59', 'x60', 'x62', 'x63', 'x69', 'x70', 'x72', 'x73',
       'x79', 'x81', 'x83', 'x90', 'x93', 'x94', 'x95', 'x98', 'x101',
       'x103', 'x106', 'x108', 'x110', 'x111', 'x112', 'x116', 'x119',
       'x121', 'x127', 'x128', 'x133', 'x135', 'x136', 'x139', 'x140',
       'x141', 'x142', 'x144', 'x145', 'x147', 'x150', 'x151', 'x161',
       'x163', 'x164', 'x167', 'x169', 'x170', 'x171', 'x174', 'x177',
       'x178', 'x179', 'x180', 'x181', 'x182', 'x184', 'x187', 'x188',
       'x189', 'x190', 'x191', 'x195', 'x200', 'x202', 'x203', 'x206',
       'x207', 'x209', 'x211', 'x215', 'x219', 'x220', 'x223', 'x225',
       'x226', 'x227', 'x229', 'x233', 'x239', 'x242', 'x243', 'x246',
       'x249', 'x251', 'x252', 'x255', 'x259', 'x263', 'x266', 'x267',
       'x269', 'x270', 'x271', 'x274', 'x279', 'x281', 'x286', 'x287',
      

In [11]:
rfecv.cv_results_

{'mean_test_score': array([-0.16224116, -0.15948638, -0.16098204, -0.1636009 , -0.16551487,
        -0.16821978, -0.16792307, -0.16971655]),
 'std_test_score': array([0.01651491, 0.0161541 , 0.01583374, 0.01776252, 0.01885396,
        0.01680881, 0.01635067, 0.01737918]),
 'split0_test_score': array([-0.13832247, -0.13465514, -0.13727295, -0.13362952, -0.13685932,
        -0.14129542, -0.1418756 , -0.14068121]),
 'split1_test_score': array([-0.15829394, -0.15736918, -0.15829914, -0.16324372, -0.16181221,
        -0.16529728, -0.1683796 , -0.1705429 ]),
 'split2_test_score': array([-0.18602491, -0.18141887, -0.182056  , -0.18471007, -0.18982308,
        -0.19099321, -0.19054984, -0.19278182]),
 'split3_test_score': array([-0.15423169, -0.15224533, -0.15301172, -0.15843744, -0.15690623,
        -0.16352325, -0.16098853, -0.16450349]),
 'split4_test_score': array([-0.17433281, -0.17174341, -0.17427039, -0.17798374, -0.18217352,
        -0.17998975, -0.17782177, -0.18007336])}

In [12]:
rfecv.ranking_

array([1, 2, 1, 6, 4, 1, 3, 7, 3, 1, 1, 1, 1, 2, 1, 1, 3, 2, 4, 7, 5, 1,
       1, 4, 2, 5, 3, 7, 4, 3, 6, 7, 1, 1, 1, 5, 1, 6, 4, 7, 5, 1, 6, 2,
       2, 1, 2, 6, 3, 1, 4, 3, 4, 3, 5, 4, 7, 1, 1, 1, 1, 3, 1, 1, 5, 2,
       5, 7, 3, 1, 1, 2, 1, 1, 3, 5, 6, 7, 6, 1, 7, 1, 2, 1, 4, 2, 2, 4,
       2, 6, 1, 4, 6, 1, 1, 1, 6, 3, 1, 4, 7, 1, 3, 1, 3, 5, 1, 5, 1, 6,
       1, 1, 1, 2, 4, 4, 1, 2, 3, 1, 6, 1, 2, 5, 2, 4, 5, 1, 1, 4, 7, 7,
       2, 1, 7, 1, 1, 2, 6, 1, 1, 1, 1, 3, 1, 1, 7, 1, 2, 4, 1, 1, 3, 5,
       5, 4, 7, 7, 2, 2, 7, 1, 6, 1, 1, 6, 3, 1, 7, 1, 1, 1, 5, 5, 1, 7,
       2, 1, 1, 1, 1, 1, 1, 3, 1, 7, 3, 1, 1, 1, 1, 1, 4, 6, 4, 1, 4, 6,
       4, 3, 1, 7, 1, 1, 2, 2, 1, 1, 4, 1, 6, 1, 6, 2, 5, 1, 6, 7, 5, 1,
       1, 4, 5, 1, 3, 1, 1, 1, 4, 1, 7, 6, 6, 1, 6, 5, 4, 6, 3, 1, 7, 7,
       1, 1, 6, 6, 1, 3, 3, 1, 5, 1, 1, 3, 2, 1, 7, 6, 4, 1, 4, 5, 7, 1,
       5, 2, 1, 1, 7, 1, 1, 1, 5, 5, 1, 7, 2, 6, 3, 1, 5, 1, 6, 5, 3, 3,
       1, 1, 4, 2, 5, 5, 7, 5, 1, 1, 1, 3, 4, 6])

In [65]:
len(rfecv.ranking_), len(rfecv.get_feature_names_out())

(300, 100)

In [66]:
X

array([[ 0.88661908,  1.42146609,  1.10345691, ...,  0.03404206,
         0.23978821,  2.41669025],
       [-0.06950958,  1.007678  ,  0.28973477, ..., -0.57177621,
         1.5297184 ,  0.65710649],
       [ 1.18707986, -0.15726531,  2.39808412, ...,  0.47989883,
         0.65131619, -0.48580281],
       ...,
       [ 0.5187474 ,  0.26190761, -3.56036828, ...,  1.24963992,
         1.31375189,  1.5736302 ],
       [-0.72134957, -0.18112951, -0.395346  , ..., -0.21437854,
         0.59573587,  0.35230313],
       [ 0.47388275,  0.43178594, -1.97444937, ...,  0.12952139,
        -0.85605538, -0.07904277]])